name: taskmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  http: ^1.2.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.10
  supabase_flutter: ^2.3.4
  connectivity_plus: ^5.0.2
  onesignal_flutter: ^5.1.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  flutter_contacts: ^1.1.9
  table_calendar: ^3.0.9
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  assets:
    - assets/logo.png
    - assets/Copy of Welcome - 1.jpg
    - assets/Copy of Welcome - 2.jpg
    - assets/blur image 1.jpg
    - assets/background.jpg
    - assets/utilisateur.png
    - assets/vectors/vector_7_x2.svg
    - assets/icons/vector_right.svg
    - assets/icons/vector_left.svg
    - assets/images/
    - .env

  uses-material-design: true

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Black.ttf
    - family: LeagueSpartanMedium
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf