name: taskmate
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  http: ^1.2.1  # Updated to latest patch version
  permission_handler: ^12.0.1
  provider: ^6.0.5
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.10  # UPDATED: Critical fix for build errors
  sqflite: ^2.4.2
  path: ^1.9.1
  supabase_flutter: ^2.3.4
  connectivity_plus: ^5.0.2
  firebase_messaging: ^14.7.20
  firebase_core: ^2.27.1
  flutter_local_notifications: ^17.2.2
  

  flutter_launcher_icons: ^0.14.4  # UPDATED: Compatible with Flutter 3.32
  json_annotation: ^4.8.1 # Added for JSON serialization
dev_dependencies:
  flutter_test:
    sdk: flutter # Corrected declaration
  intl: ^0.20.2
  table_calendar: ^3.0.9  # UPDATED: Latest compatible version
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6 # Added for code generation
  json_serializable: ^6.7.1 # Added for JSON serialization

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  assets:
    - assets/logo.png
    - assets/Copy of Welcome - 1.jpg
    - assets/Copy of Welcome - 2.jpg
    - assets/blur image 1.jpg
    - assets/background.jpg
    - assets/utilisateur.png
    - assets/vectors/vector_7_x2.svg
    - assets/icons/vector_right.svg
    - assets/icons/vector_left.svg
    - assets/images/

  uses-material-design: true

  fonts:
    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Black.ttf
    - family: LeagueSpartanMedium
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf